spring:
  datasource:
    url: jdbc:sqlite:orders.db
    driver-class-name: org.sqlite.JDBC
    username: ""
    password: ""

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080